import { bgColors, textColors } from "./theme";

export const scheduleConfig = [
  {
    startTime: "00:00",
    endTime: "06:00",
    title: "Sleep",
    // description: "Sleep Time",
    bgColor: bgColors[7],
    color: textColors[7],
  },
  {
    startTime: "06:00",
    endTime: "07:00",
    title: "Breakfirst",
    // description: "Have a breakfirst",
    bgColor: bgColors[1],
    color: textColors[1],
  },
  {
    startTime: "07:00",
    endTime: "08:00",
    title: "Traffic",
    // description: "Go to school & work",
    bgColor: bgColors[4],
    color: textColors[4],
  },
  {
    startTime: "08:00",
    endTime: "09:30",
    title: "Study",
    // description: "Learn good things",
    bgColor: bgColors[5],
    color: textColors[5],
  },
  {
    startTime: "09:30",
    endTime: "11:30",
    title: "Work",
    bgColor: bgColors[6],
    color: textColors[6],
  },
  {
    startTime: "11:30",
    endTime: "13:00",
    title: "Lunch",
    bgColor: bgColors[1],
    color: textColors[1],
  },
  {
    startTime: "13:00",
    endTime: "15:00",
    title: "Work",
    bgColor: bgColors[6],
    color: textColors[6],
  },
  {
    startTime: "15:00",
    endTime: "17:00",
    title: "Study",
    bgColor: bgColors[5],
    color: textColors[5],
  },
  {
    startTime: "17:00",
    endTime: "18:00",
    title: "Supper",
    bgColor: bgColors[1],
    color: textColors[1],
  },
  {
    startTime: "18:00",
    endTime: "19:00",
    title: "Study",
    bgColor: bgColors[5],
    color: textColors[5],
  },
  {
    startTime: "19:00",
    endTime: "20:00",
    title: "Relex",
    bgColor: bgColors[9],
    color: textColors[9],
  },
  {
    startTime: "20:00",
    endTime: "21:00",
    title: "Wash & Clean",
    bgColor: bgColors[2],
    color: textColors[2],
  },
  {
    startTime: "21:00",
    endTime: "23:59",
    title: "Sleep",
    bgColor: bgColors[7],
    color: textColors[7],
  },
];
